Created types and sequences.
canbula/PythonProgramming pull request #32
Opened 2024-02-23 21:39 UTC by o-goldensail

## Describe your changes

## Checklist
- [ ] I have read the [CONTRIBUTING]
- [ ] I have performed a self-review of my own code
- [ ] I have run the code locally and it works as expected
- [ ] I have commented my code, particularly in hard-to-understand areas

## Screenshots (if appropriate)

2024-02-23 21:39 UTC, o-goldensail commented
My github desktop decided to destroy itself so i had to make a new pull request.

2024-02-25 08:28 UTC, canbula requested changes
Using Turkish special characters, such as `ı`, is not allowed for module names.

2024-02-28 18:34 UTC, canbula requested changes
Check the test results.

2024-03-02 06:04 UTC, canbula approved these changes

2024-03-02 06:04 UTC, merged