Create emails_mert_can_fidan.py
canbula/PythonProgramming pull request #94
Opened 2024-03-14 02:23 UTC by usrmertc

## My Changes
 
I created `Emails` class which satisfies `test_emails.py`. 
 
## Checklist
- [x] I have read [CONTRIBUTING].
- [x] I have performed a self-review of my own code.
- [x] I have run the code locally and it works as explained.
- [x] I have commented my code, particularly in hard-to-understand areas

2024-03-14 06:57 UTC, canbula requested changes
I want you to check also if the string includes a dot `.` not just `@`.

2024-03-14 12:00 UTC, usrmertc commented
I updated my code. I used regex instead of simply checks '@' and '.'. I just want to make it more like real email checks but if is not acceptable I can change that with simple one.

2024-03-14 12:23 UTC, usrmertc commented
Sorry. I saw the test update later and, I updated my code again. Now it's satisfy new test requirements.

2024-03-16 14:57 UTC, canbula approved these changes

2024-03-16 14:57 UTC, merged